# Generated by Django 3.0.5 on 2024-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=30)),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('idprrof', models.CharField(max_length=30)),
                ('idprroffile', models.FileField(max_length=254, upload_to='')),
                ('cheakindate', models.DateField()),
                ('cheakintime', models.TimeField()),
                ('cheakoutdate', models.DateField()),
                ('cheakouttime', models.TimeField()),
                ('timestap', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
