# Generated by Django 3.0.5 on 2024-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.IntegerField()),
                ('table', models.IntegerField()),
                ('room', models.IntegerField()),
                ('customer', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('cheakindate', models.DateField()),
                ('cheakintime', models.TimeField()),
                ('cheakoutdate', models.DateField()),
                ('cheakouttime', models.TimeField()),
                ('decription', models.CharField(max_length=50)),
                ('totalamount', models.IntegerField()),
                ('gstamount', models.IntegerField()),
                ('netamount', models.IntegerField()),
                ('timestap', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
