# Generated by Django 3.0.5 on 2024-02-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0007_paymentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentData',
        ),
    ]
