# Generated by Django 3.0.5 on 2024-02-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0012_auto_20240213_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentData',
        ),
    ]
