# Generated by Django 3.1.8 on 2024-04-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0014_paymentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentData',
        ),
    ]
