# Generated by Django 3.1.8 on 2024-04-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0016_paymentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillData',
        ),
    ]
