# Generated by Django 3.1.8 on 2024-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0019_auto_20240404_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdata',
            name='quntity',
            field=models.IntegerField(),
        ),
    ]
