# Generated by Django 3.1.8 on 2024-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0020_auto_20240404_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='billdata',
            name='quntity',
        ),
        migrations.RemoveField(
            model_name='billdata',
            name='rate',
        ),
    ]
