# Generated by Django 3.1.8 on 2024-04-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelMSApp', '0021_auto_20240404_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentData',
        ),
    ]
